Feature/preview
FlockOfBirds/range-slider pull request #3
Opened 2017-06-01 15:28 UTC by akileng56

- Add preview

2017-06-02 09:06 UTC, Andries-Smit requested changes

2017-06-02 09:06 UTC, Andries-Smit commented on Gruntfile.js
> +const webpackConfigRelease = [ {}, {} ];
google maps repo has a nicer way of doing this. please use that

2017-06-02 09:06 UTC, Andries-Smit commented on src/RangeSlider.webmodeler.ts
> +    private addPreviewStyle(styleClass: string, styleId: string) {
Use new `export function getPreviewCss()`

2017-06-02 09:06 UTC, Andries-Smit commented on src/components/RangeSliderContainer.ts
> +        const disabled = !this.props.mxObject || this.props.readOnly;
Checking isReadonlyAttr is required
readOnly does not check the mxObject attributes, only if the form in the webmodeler is configured to be rendering as read only

Previous version was incorrectly checking `stepAttribute` as this is not the attribute that you going to change, it need to check for both `lowerBoundAttribute` and `lowerBoundAttribute` to be writable.

2017-06-02 09:06 UTC, Andries-Smit commented on src/components/RangeSliderContainer.ts
> +            console.log("Failed to parse style", style, error);
Your linter should complain about this. please check if is running and up to date.
Please add `// tslint:disable-next-line no-console` to fix it aftewards

2017-06-02 09:06 UTC, Andries-Smit commented on src/components/RangeSliderContainer.ts
>          if (mxObject && Array.isArray(value) && value.length > 0) {
Please remove newline on 144 
https://github.com/FlockOfBirds/range-slider/pull/3/files#diff-faef39ffac314d6b386a3d82cc3ed72bR145

2017-06-02 09:06 UTC, Andries-Smit commented on src/components/RangeSliderContainer.ts
>          if (mxObject && Array.isArray(value) && value.length > 0) {
No need for (error) parentheses line 169
https://github.com/FlockOfBirds/range-slider/pull/3/files#diff-faef39ffac314d6b386a3d82cc3ed72bR169

2017-06-02 09:06 UTC, Andries-Smit commented on src/components/RangeSliderContainer.ts
>      }
Though it might be working. its is confusing to read. please rewrite
`this.subscriptionCallback = mxObject => () => this.setState(this.updateValues(mxObject))`

2017-06-02 09:06 UTC, Andries-Smit commented on src/components/RangeSliderContainer.ts
>          if (mxObject && Array.isArray(value) && value.length > 0) {
No need to pass undefined as a last parameter, omitted parameters are already `undefined` Line 152 153 154 156
https://github.com/FlockOfBirds/range-slider/pull/3/files#diff-faef39ffac314d6b386a3d82cc3ed72bR152

2017-06-02 09:06 UTC, Andries-Smit commented on src/RangeSlider.webmodeler.ts
> +        this.warnings = RangeSliderContainer.validateSettings({
Noting is done with the warning.

Please output the in an Alert component, but also render you widget as good as it gets.

2017-06-02 09:11 UTC, Andries-Smit commented on src/RangeSlider.webmodeler.ts
> +        this.warnings = RangeSliderContainer.validateSettings({
I mis interpenetrated the code. side-effect...

May It is neater to mix it in with the returned conversion props results or pass it as an argument into the function.

2017-06-07 10:03 UTC, djkwagala commented on package.json
>      "@types/dojo": "^1.9.37",
What are you using Dojo for?

2017-06-07 10:03 UTC, djkwagala commented on typings/rc-slider.d.ts
>  declare module "rc-slider" {
Why did you have to add this file? why not @types/rc_slider. 
Alternatively update the typings, and create pull request to https://www.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rc-slider
indicate the change to  https://github.com/mantasmarcinkus/.

2017-06-07 10:03 UTC, djkwagala commented on typings/tooltip.d.ts
> +declare module "rc-tooltip" {
Why did you have to add this file? why not .
Alternatively update the typings, and create pull request to https://www.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/rc-tooltip
indicate the change to https://rhysd.github.io.

2017-06-07 10:03 UTC, djkwagala commented on Gruntfile.js
> +    webpackConfigRelease.push(configRelease)
missing ;

2017-06-07 10:03 UTC, djkwagala commented on Gruntfile.js
> +webpackConfig.forEach(function (currentWebpackConfig) {
remove space between `function` and `(currentWebpackConfig)`

2017-06-07 10:03 UTC, djkwagala commented on src/RangeSlider.xml
>                  <enumerationValue key="inverse">Inverse</enumerationValue>
Missing color for "Default"

2017-06-07 11:48 UTC, akileng56 commented on src/RangeSlider.xml
>                  <enumerationValue key="inverse">Inverse</enumerationValue>
The default color happens to be the color used by Lib when slider is disabled or has no context... This might be confusing..

2017-06-07 11:48 UTC, akileng56 commented on Gruntfile.js
> +    webpackConfigRelease.push(configRelease)
added

2017-06-07 11:51 UTC, akileng56 commented on typings/tooltip.d.ts
> +declare module "rc-tooltip" {
It might be working for others..... on my side it fails i think when bundling...cause it doesn't pick the default method or class...

2017-06-07 11:51 UTC, akileng56 commented on package.json
>      "@types/dojo": "^1.9.37",
Removed

2017-06-12 15:18 UTC, merged